int is_valid_nickname_character(char c);
int validate_and_copy_nickname(const char *source, size_t nickname_length, char *nickname_destination);
int extract_nickname_from_argument(const char *argument, char *nickname_destination);
int connect_to_server(const char *server_ip, const char *server_port);
int receive_and_print_server_message(int socket_fd);
int fill_and_send_message_header(int socket_fd, struct message *s_message, int pld_len, const char *nick_sender, enum msg_type type, const char *infos);
int is_quit_command(const char *message);
int is_who_command(const char *message);
int send_quit_request(int socket_fd, struct message *s_message);
int send_nickname_change_request(int socket_fd, struct message *s_message, char *message);
int send_nickname_list_request(int socket_fd, struct message *s_message);
int send_nickname_info_request(int socket_fd, struct message *s_message, char *message);
int send_broadcast_message(int socket_fd, struct message *s_message, char *message);
int send_private_message(int socket_fd, struct message *s_message, char *message);
int send_echo_message(int socket_fd, struct message *s_message, char *message, int message_size);